basePath: /
definitions:
  request.ReqSignIn:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      serviceType:
        enum:
        - game
        type: string
    required:
    - email
    - password
    - serviceType
    type: object
host: localhost:6000
info:
  contact: {}
  description: This is the API documentation for the Joker Backend services.
  title: Joker Backend API
  version: "1.0"
paths:
  /v0.1/auth/signin:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재
        USER_GOOGLE_ALREADY_EXISTED : 구글 계정이 이미 존재
        PASSWORD_NOT_MATCH : 비밀번호가 일치하지 않음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: 이메일, 비밀번호, 서비스 타입
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqSignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 로그인
      tags:
      - auth
schemes:
- http
swagger: "2.0"
